## 9. Part 2 - Deep Learning Hyperparameter Optimization

### 1. Importing libraries

### 2. Importing data

### 3. Data wrangling

### 4. Data reshaping

### 5. Data splitting

### 6. Bayesian hyperparameter optimization

### 7. Running RNN with optimized hyperparameters

### 8. Confusion matrix

#### 1. Importing libraries

In [11]:
# Importing libraries
import pandas as pd
import numpy as np
import seaborn as sns
import os
import operator
import time
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from numpy import unique
from numpy import reshape
from keras.models import Sequential
from sklearn.model_selection import cross_val_score
from keras.layers import Conv1D, Conv2D, Dense, Dropout, BatchNormalization, Flatten, MaxPooling1D, LSTM
from tensorflow.keras.layers import Dense, Dropout
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.optimizers import Adam, SGD, RMSprop, Adadelta, Adagrad, Adamax, Nadam, Ftrl
from keras.callbacks import EarlyStopping, ModelCheckpoint
from scikeras.wrappers import KerasClassifier
from math import floor
from sklearn.metrics import make_scorer, accuracy_score
from bayes_opt import BayesianOptimization
from sklearn.model_selection import StratifiedKFold
from keras.layers import LeakyReLU
LeakyReLU = LeakyReLU(alpha=0.1)
import warnings
warnings.filterwarnings('ignore')
pd.set_option("display.max_columns", None)

C:\Users\Priya\anaconda3\Lib\site-packages\keras\src\layers\activations\leaky_relu.py:41: UserWarning: Argument `alpha` is deprecated. Use `negative_slope` instead.
  warnings.warn(

#### 2. Importing data

In [13]:
path = r'C:\Users\Priya\OneDrive\Documents\CareerFoundry\Machine Learning'

In [14]:
path

'C:\\Users\\Priya\\OneDrive\\Documents\\CareerFoundry\\Machine Learning'

In [15]:
# Importing the cleaned weather observations data set
climate_cleaned = pd.read_csv(os.path.join(path, 'Achievement 2', 'Data Sets', 'weather_cleaned.csv'), index_col = False)

In [16]:
# Checking the shape of the dataframe
climate_cleaned.shape

(22950, 136)

In [17]:
# Viewing the first five rows of the dataframe
climate_cleaned.head()

,Unnamed: 0,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,BELGRADE_humidity,BELGRADE_pressure,BELGRADE_global_radiation,BELGRADE_precipitation,BELGRADE_sunshine,BELGRADE_temp_mean,BELGRADE_temp_min,BELGRADE_temp_max,BUDAPEST_cloud_cover,BUDAPEST_humidity,BUDAPEST_pressure,BUDAPEST_global_radiation,BUDAPEST_precipitation,BUDAPEST_sunshine,BUDAPEST_temp_mean,BUDAPEST_temp_min,BUDAPEST_temp_max,DEBILT_cloud_cover,DEBILT_humidity,DEBILT_pressure,DEBILT_global_radiation,DEBILT_precipitation,DEBILT_sunshine,DEBILT_temp_mean,DEBILT_temp_min,DEBILT_temp_max,DUSSELDORF_cloud_cover,DUSSELDORF_humidity,DUSSELDORF_pressure,DUSSELDORF_global_radiation,DUSSELDORF_precipitation,DUSSELDORF_sunshine,DUSSELDORF_temp_mean,DUSSELDORF_temp_min,DUSSELDORF_temp_max,HEATHROW_cloud_cover,HEATHROW_humidity,HEATHROW_pressure,HEATHROW_global_radiation,HEATHROW_precipitation,HEATHROW_sunshine,HEATHROW_temp_mean,HEATHROW_temp_min,HEATHROW_temp_max,KASSEL_cloud_cover,KASSEL_humidity,KASSEL_pressure,KASSEL_global_radiation,KASSEL_precipitation,KASSEL_sunshine,KASSEL_temp_mean,KASSEL_temp_min,KASSEL_temp_max,LJUBLJANA_cloud_cover,LJUBLJANA_humidity,LJUBLJANA_pressure,LJUBLJANA_global_radiation,LJUBLJANA_precipitation,LJUBLJANA_sunshine,LJUBLJANA_temp_mean,LJUBLJANA_temp_min,LJUBLJANA_temp_max,MAASTRICHT_cloud_cover,MAASTRICHT_humidity,MAASTRICHT_pressure,MAASTRICHT_global_radiation,MAASTRICHT_precipitation,MAASTRICHT_sunshine,MAASTRICHT_temp_mean,MAASTRICHT_temp_min,MAASTRICHT_temp_max,MADRID_cloud_cover,MADRID_humidity,MADRID_pressure,MADRID_global_radiation,MADRID_precipitation,MADRID_sunshine,MADRID_temp_mean,MADRID_temp_min,MADRID_temp_max,MUNCHENB_cloud_cover,MUNCHENB_humidity,MUNCHENB_pressure,MUNCHENB_global_radiation,MUNCHENB_precipitation,MUNCHENB_sunshine,MUNCHENB_temp_mean,MUNCHENB_temp_min,MUNCHENB_temp_max,OSLO_cloud_cover,OSLO_humidity,OSLO_pressure,OSLO_global_radiation,OSLO_precipitation,OSLO_sunshine,OSLO_temp_mean,OSLO_temp_min,OSLO_temp_max,SONNBLICK_cloud_cover,SONNBLICK_humidity,SONNBLICK_pressure,SONNBLICK_global_radiation,SONNBLICK_precipitation,SONNBLICK_sunshine,SONNBLICK_temp_mean,SONNBLICK_temp_min,SONNBLICK_temp_max,STOCKHOLM_cloud_cover,STOCKHOLM_humidity,STOCKHOLM_pressure,STOCKHOLM_global_radiation,STOCKHOLM_precipitation,STOCKHOLM_sunshine,STOCKHOLM_temp_mean,STOCKHOLM_temp_min,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,0,7,0.85,1.018,0.32,0.09,0.7,6.5,0.8,10.9,1,0.81,1.0195,0.88,0.00,7.0,3.7,-0.9,7.9,4,0.67,1.017,0.44,0.01,2.3,2.4,-0.4,5.1,7,0.85,1.0032,0.07,0.25,0.0,9.3,7.4,11.0,8,0.83,1.0161,0.12,0.08,0.0,10.0,7.0,11.5,7,0.91,1.0010,0.13,0.22,0.0,10.6,9.4,8.3,8,0.82,1.0094,0.28,0.48,1.6,7.9,3.9,9.4,8,1.00,1.0173,0.20,0.00,0.0,-0.6,-1.9,0.5,7,0.83,1.0063,0.22,0.32,1.0,9.5,8.5,11.1,6,0.92,1.0260,0.53,0.0,1.4,7.6,4.4,10.8,5,0.67,1.0304,0.20,0.10,0.0,6.9,1.1,10.4,8,0.98,0.9978,0.04,1.14,0.0,4.9,3.8,5.9,4,0.73,1.0304,0.48,0.01,2.3,-5.9,-8.5,-3.2,5,0.98,1.0114,0.05,0.32,0.0,4.2,2.2,4.9,5,0.88,1.0003,0.45,0.34,4.7,8.5,6.0,10.9
1,1,6,0.84,1.018,0.36,1.05,1.1,6.1,3.3,10.1,6,0.84,1.0172,0.25,0.00,0.0,2.9,2.2,4.4,4,0.67,1.017,0.18,0.31,0.0,2.3,1.4,3.1,8,0.90,1.0056,0.14,0.06,0.1,7.7,6.4,8.3,8,0.89,1.0161,0.18,0.66,0.5,8.2,7.4,11.0,7,0.98,1.0051,0.13,0.23,0.0,6.1,3.9,10.6,8,0.86,1.0086,0.12,0.27,0.0,7.7,6.8,9.1,6,0.94,1.0173,0.56,0.13,3.2,2.1,-1.3,5.5,8,0.92,1.0062,0.17,1.34,0.4,8.6,7.5,9.9,7,0.86,1.0254,0.46,0.0,0.9,9.8,7.4,12.2,6,0.72,1.0292,0.61,0.30,5.1,6.2,4.2,10.2,8,0.62,1.0139,0.04,0.00,0.0,3.4,2.8,4.9,6,0.97,1.0292,0.21,0.61,0.0,-9.5,-10.5,-8.5,5,0.62,1.0114,0.05,0.06,0.0,4.0,3.0,5.0,7,0.91,1.0007,0.25,0.84,0.7,8.9,5.6,12.1
2,2,8,0.90,1.018,0.18,0.30,0.0,8.5,5.1,9.9,6,0.77,1.0179,0.67,0.00,3.5,3.1,-0.5,6.4,4,0.67,1.017,0.30,0.00,0.6,2.7,1.7,5.3,6,0.92,1.0165,0.28,0.01,3.0,6.8,4.6,9.9,7,0.95,1.0161,0.12,0.07,0.0,7.1,6.9,9.1,8,0.96,1.0166,0.15,0.07,0.1,8.4,6.1,12.2,7,0.91,1.0129,0.12,0.60,0.0,6.5,6.0,8.0,8,0.96,1.0173,0.20,0.12,0.0,4.6,0.9,6.3,7,0.97,1.0167,0.12,0.46,0.0,6.9,5.5,9.9,5,0.90,1.0287,0.63,0.0,2.3,8.6,6.4,10.8,6,0.91,1.0320,0.20,0.30,0.0,5.8,4.0,8.0,8,0.69,1.0234,0.04,0.08,0.0,1.9,0.6,3.1,8,0.93,1.0320,0.21,3.20,0.0,-9.5,-10.0,-8.9,5,0.69,1.0114,0.05,0.02,0.0,2.4,1.3,4.1,7,0.91,1.0096,0.17,0.08,0.1,10.5,8.1,12.9
3,3,3,0.92,1.018,0.58,0.00,4.1,6.3,3.8,10.6,8,0.93,1.0268,0.25,0.00,0.0,2.0,-2.0,3.0,4,0.67,1.017,0.19,0.00,0.0,2.0,0.4,4.4,8,0.95,1.0265,0.08,0.09,0.0,6.7,3.6,10.1,8,0.86,1.0161,0.12,0.02,0.0,6.8,3.6,8.0,8,0.98,1.0230,0.13,0.00,0.0,9.4,6.7,8.9,8,0.87,1.0290,0.12,0.00,0.0,5.8,5.2,6.5,6,0.94,1.0173,0.49,0.00,2.2,3.2,1.0,7.0,7,0.89,1.0277,0.16,0.00,0.3,7.0,3.0,10.0,0,0.75,1.0281,1.16,0.0,8.7,10.3,4.5,16.1,6,0.90,1.0443,0.20,0.01,0.0,3.9,3.2,5.4,8,0.98,1.0244,0.04,0.35,0.0,3.0,0.4,4.9,5,0.93,1.0443,0.22,1.10,0.0,-11.5,-12.9,-10.0,5,0.98,1.0114,0.05,0.00,0.0,1.2,0.4,2.3,7,0.86,1.0184,0.13,0.98,0.0,7.4,7.3,10.6
4,4,6,0.95,1.018,0.65,0.14,5.4,3.0,-0.7,6.0,8,0.99,1.0286,0.25,0.06,0.0,2.0,0.7,2.8,4,0.67,1.017,0.19,0.00,0.0,2.5,1.1,5.3,6,0.90,1.0243,0.04,0.39,0.0,8.0,2.4,11.2,7,0.92,1.0161,0.12,0.62,0.0,7.7,6.2,11.0,5,0.84,1.0275,0.30,0.00,2.1,8.9,8.9,7.2,7,0.86,1.0262,0.13,0.71,0.0,5.4,3.7,6.0,7,0.94,1.0173,0.20,0.00,0.0,3.6,0.4,4.8,7,0.92,1.0259,0.12,0.56,0.0,8.1,2.5,11.1,2,0.64,1.0269,1.10,0.0,7.8,12.1,8.2,16.0,5,0.85,1.0430,0.65,0.96,5.6,1.8,-3.0,6.0,8,0.96,1.0092,0.05,0.26,0.0,3.7,2.9,4.9,2,0.75,1.0430,0.72,0.01,6.1,-9.3,-12.0,-6.5,5,0.96,1.0114,0.05,1.32,0.0,3.3,0.8,4.3,3,0.80,1.0328,0.46,0.00,5.7,5.7,3.0,8.4

In [18]:
# Dropping the Unnamed: 0 column
climate_cleaned = climate_cleaned.drop(['Unnamed: 0'], axis=1)

In [19]:
# Checking the shape of the dataframe
climate_cleaned.shape

(22950, 135)

In [20]:
# Checking if the Unnamed: 0 column was dropped
climate_cleaned.head()

,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,BELGRADE_humidity,BELGRADE_pressure,BELGRADE_global_radiation,BELGRADE_precipitation,BELGRADE_sunshine,BELGRADE_temp_mean,BELGRADE_temp_min,BELGRADE_temp_max,BUDAPEST_cloud_cover,BUDAPEST_humidity,BUDAPEST_pressure,BUDAPEST_global_radiation,BUDAPEST_precipitation,BUDAPEST_sunshine,BUDAPEST_temp_mean,BUDAPEST_temp_min,BUDAPEST_temp_max,DEBILT_cloud_cover,DEBILT_humidity,DEBILT_pressure,DEBILT_global_radiation,DEBILT_precipitation,DEBILT_sunshine,DEBILT_temp_mean,DEBILT_temp_min,DEBILT_temp_max,DUSSELDORF_cloud_cover,DUSSELDORF_humidity,DUSSELDORF_pressure,DUSSELDORF_global_radiation,DUSSELDORF_precipitation,DUSSELDORF_sunshine,DUSSELDORF_temp_mean,DUSSELDORF_temp_min,DUSSELDORF_temp_max,HEATHROW_cloud_cover,HEATHROW_humidity,HEATHROW_pressure,HEATHROW_global_radiation,HEATHROW_precipitation,HEATHROW_sunshine,HEATHROW_temp_mean,HEATHROW_temp_min,HEATHROW_temp_max,KASSEL_cloud_cover,KASSEL_humidity,KASSEL_pressure,KASSEL_global_radiation,KASSEL_precipitation,KASSEL_sunshine,KASSEL_temp_mean,KASSEL_temp_min,KASSEL_temp_max,LJUBLJANA_cloud_cover,LJUBLJANA_humidity,LJUBLJANA_pressure,LJUBLJANA_global_radiation,LJUBLJANA_precipitation,LJUBLJANA_sunshine,LJUBLJANA_temp_mean,LJUBLJANA_temp_min,LJUBLJANA_temp_max,MAASTRICHT_cloud_cover,MAASTRICHT_humidity,MAASTRICHT_pressure,MAASTRICHT_global_radiation,MAASTRICHT_precipitation,MAASTRICHT_sunshine,MAASTRICHT_temp_mean,MAASTRICHT_temp_min,MAASTRICHT_temp_max,MADRID_cloud_cover,MADRID_humidity,MADRID_pressure,MADRID_global_radiation,MADRID_precipitation,MADRID_sunshine,MADRID_temp_mean,MADRID_temp_min,MADRID_temp_max,MUNCHENB_cloud_cover,MUNCHENB_humidity,MUNCHENB_pressure,MUNCHENB_global_radiation,MUNCHENB_precipitation,MUNCHENB_sunshine,MUNCHENB_temp_mean,MUNCHENB_temp_min,MUNCHENB_temp_max,OSLO_cloud_cover,OSLO_humidity,OSLO_pressure,OSLO_global_radiation,OSLO_precipitation,OSLO_sunshine,OSLO_temp_mean,OSLO_temp_min,OSLO_temp_max,SONNBLICK_cloud_cover,SONNBLICK_humidity,SONNBLICK_pressure,SONNBLICK_global_radiation,SONNBLICK_precipitation,SONNBLICK_sunshine,SONNBLICK_temp_mean,SONNBLICK_temp_min,SONNBLICK_temp_max,STOCKHOLM_cloud_cover,STOCKHOLM_humidity,STOCKHOLM_pressure,STOCKHOLM_global_radiation,STOCKHOLM_precipitation,STOCKHOLM_sunshine,STOCKHOLM_temp_mean,STOCKHOLM_temp_min,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,7,0.85,1.018,0.32,0.09,0.7,6.5,0.8,10.9,1,0.81,1.0195,0.88,0.00,7.0,3.7,-0.9,7.9,4,0.67,1.017,0.44,0.01,2.3,2.4,-0.4,5.1,7,0.85,1.0032,0.07,0.25,0.0,9.3,7.4,11.0,8,0.83,1.0161,0.12,0.08,0.0,10.0,7.0,11.5,7,0.91,1.0010,0.13,0.22,0.0,10.6,9.4,8.3,8,0.82,1.0094,0.28,0.48,1.6,7.9,3.9,9.4,8,1.00,1.0173,0.20,0.00,0.0,-0.6,-1.9,0.5,7,0.83,1.0063,0.22,0.32,1.0,9.5,8.5,11.1,6,0.92,1.0260,0.53,0.0,1.4,7.6,4.4,10.8,5,0.67,1.0304,0.20,0.10,0.0,6.9,1.1,10.4,8,0.98,0.9978,0.04,1.14,0.0,4.9,3.8,5.9,4,0.73,1.0304,0.48,0.01,2.3,-5.9,-8.5,-3.2,5,0.98,1.0114,0.05,0.32,0.0,4.2,2.2,4.9,5,0.88,1.0003,0.45,0.34,4.7,8.5,6.0,10.9
1,6,0.84,1.018,0.36,1.05,1.1,6.1,3.3,10.1,6,0.84,1.0172,0.25,0.00,0.0,2.9,2.2,4.4,4,0.67,1.017,0.18,0.31,0.0,2.3,1.4,3.1,8,0.90,1.0056,0.14,0.06,0.1,7.7,6.4,8.3,8,0.89,1.0161,0.18,0.66,0.5,8.2,7.4,11.0,7,0.98,1.0051,0.13,0.23,0.0,6.1,3.9,10.6,8,0.86,1.0086,0.12,0.27,0.0,7.7,6.8,9.1,6,0.94,1.0173,0.56,0.13,3.2,2.1,-1.3,5.5,8,0.92,1.0062,0.17,1.34,0.4,8.6,7.5,9.9,7,0.86,1.0254,0.46,0.0,0.9,9.8,7.4,12.2,6,0.72,1.0292,0.61,0.30,5.1,6.2,4.2,10.2,8,0.62,1.0139,0.04,0.00,0.0,3.4,2.8,4.9,6,0.97,1.0292,0.21,0.61,0.0,-9.5,-10.5,-8.5,5,0.62,1.0114,0.05,0.06,0.0,4.0,3.0,5.0,7,0.91,1.0007,0.25,0.84,0.7,8.9,5.6,12.1
2,8,0.90,1.018,0.18,0.30,0.0,8.5,5.1,9.9,6,0.77,1.0179,0.67,0.00,3.5,3.1,-0.5,6.4,4,0.67,1.017,0.30,0.00,0.6,2.7,1.7,5.3,6,0.92,1.0165,0.28,0.01,3.0,6.8,4.6,9.9,7,0.95,1.0161,0.12,0.07,0.0,7.1,6.9,9.1,8,0.96,1.0166,0.15,0.07,0.1,8.4,6.1,12.2,7,0.91,1.0129,0.12,0.60,0.0,6.5,6.0,8.0,8,0.96,1.0173,0.20,0.12,0.0,4.6,0.9,6.3,7,0.97,1.0167,0.12,0.46,0.0,6.9,5.5,9.9,5,0.90,1.0287,0.63,0.0,2.3,8.6,6.4,10.8,6,0.91,1.0320,0.20,0.30,0.0,5.8,4.0,8.0,8,0.69,1.0234,0.04,0.08,0.0,1.9,0.6,3.1,8,0.93,1.0320,0.21,3.20,0.0,-9.5,-10.0,-8.9,5,0.69,1.0114,0.05,0.02,0.0,2.4,1.3,4.1,7,0.91,1.0096,0.17,0.08,0.1,10.5,8.1,12.9
3,3,0.92,1.018,0.58,0.00,4.1,6.3,3.8,10.6,8,0.93,1.0268,0.25,0.00,0.0,2.0,-2.0,3.0,4,0.67,1.017,0.19,0.00,0.0,2.0,0.4,4.4,8,0.95,1.0265,0.08,0.09,0.0,6.7,3.6,10.1,8,0.86,1.0161,0.12,0.02,0.0,6.8,3.6,8.0,8,0.98,1.0230,0.13,0.00,0.0,9.4,6.7,8.9,8,0.87,1.0290,0.12,0.00,0.0,5.8,5.2,6.5,6,0.94,1.0173,0.49,0.00,2.2,3.2,1.0,7.0,7,0.89,1.0277,0.16,0.00,0.3,7.0,3.0,10.0,0,0.75,1.0281,1.16,0.0,8.7,10.3,4.5,16.1,6,0.90,1.0443,0.20,0.01,0.0,3.9,3.2,5.4,8,0.98,1.0244,0.04,0.35,0.0,3.0,0.4,4.9,5,0.93,1.0443,0.22,1.10,0.0,-11.5,-12.9,-10.0,5,0.98,1.0114,0.05,0.00,0.0,1.2,0.4,2.3,7,0.86,1.0184,0.13,0.98,0.0,7.4,7.3,10.6
4,6,0.95,1.018,0.65,0.14,5.4,3.0,-0.7,6.0,8,0.99,1.0286,0.25,0.06,0.0,2.0,0.7,2.8,4,0.67,1.017,0.19,0.00,0.0,2.5,1.1,5.3,6,0.90,1.0243,0.04,0.39,0.0,8.0,2.4,11.2,7,0.92,1.0161,0.12,0.62,0.0,7.7,6.2,11.0,5,0.84,1.0275,0.30,0.00,2.1,8.9,8.9,7.2,7,0.86,1.0262,0.13,0.71,0.0,5.4,3.7,6.0,7,0.94,1.0173,0.20,0.00,0.0,3.6,0.4,4.8,7,0.92,1.0259,0.12,0.56,0.0,8.1,2.5,11.1,2,0.64,1.0269,1.10,0.0,7.8,12.1,8.2,16.0,5,0.85,1.0430,0.65,0.96,5.6,1.8,-3.0,6.0,8,0.96,1.0092,0.05,0.26,0.0,3.7,2.9,4.9,2,0.75,1.0430,0.72,0.01,6.1,-9.3,-12.0,-6.5,5,0.96,1.0114,0.05,1.32,0.0,3.3,0.8,4.3,3,0.80,1.0328,0.46,0.00,5.7,5.7,3.0,8.4

In [21]:
# Importing the pleasant weather dataset
pleasantweather = pd.read_csv(os.path.join(path, 'Achievement 1', 'Data Sets', 'Dataset-Answers-Weather_Prediction_Pleasant_Weather.csv'), index_col = False)

In [22]:
# Checking the shape of the pleasantweather dataset
pleasantweather.shape

(22950, 16)

In [23]:
# Viewing the first five rows of the pleasant weather dataset
pleasantweather.head()

,DATE,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,19600101,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,19600102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,19600103,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,19600104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,19600105,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

#### 3. Data wrangling

In [25]:
# Removing the limit on the number of rows that can be shown
pd.options.display.max_rows = None

In [26]:
# Dropping the DATE column from the pleasantweather dataframe
pleasantweather = pleasantweather.drop(['DATE'], axis=1)

In [27]:
# Checking the shape of the pleasantweather dataframe
pleasantweather.shape

(22950, 15)

In [28]:
# Viewing the first five rows of the pleasantweather dataframe
pleasantweather.head()

,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

#### 4. Data reshaping

In [30]:
# Renaming the climate_cleaned and pleasantweather dataframes to X and y, respectively
X = climate_cleaned
y = pleasantweather

In [31]:
# Convert X and Y into arrays
X = np.array(X)
y = np.array(y)

In [32]:
# Viewing X
X

array([[ 7.    ,  0.85  ,  1.018 , ...,  8.5   ,  6.    , 10.9   ],
       [ 6.    ,  0.84  ,  1.018 , ...,  8.9   ,  5.6   , 12.1   ],
       [ 8.    ,  0.9   ,  1.018 , ..., 10.5   ,  8.1   , 12.9   ],
       ...,
       [ 4.    ,  0.76  ,  1.0227, ..., 10.7   ,  7.9   , 13.5   ],
       [ 5.    ,  0.8   ,  1.0212, ..., 10.7   ,  7.9   , 13.5   ],
       [ 5.    ,  0.84  ,  1.0193, ..., 10.7   ,  7.9   , 13.5   ]])

In [33]:
# Viewing y
y

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [34]:
# Reshaping X
X = X.reshape(-1,15,9)

In [35]:
# Checking if X was reshaped
X.shape

(22950, 15, 9)

In [36]:
# Checking the shape of y
y.shape

(22950, 15)

In [37]:
# Using argmax to transform y
y =  np.argmax(y, axis = 1)
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [38]:
# Checking the shape of y
y.shape

(22950,)

In [39]:
# Checking the layout of y
from sklearn.utils.multiclass import type_of_target
type_of_target(y)

'multiclass'

#### 5. Data splitting

In [41]:
# Splitting the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [42]:
# Printing the shapes of X_train, X_test, y_train, and y_test
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(17212, 15, 9) (17212,)
(5738, 15, 9) (5738,)

#### 6. Bayesian hyperparameter optimization

In [44]:
timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = 15
# Make scorer accuracy
score_acc = make_scorer(accuracy_score)

In [45]:
# Creating function
def bay_area(neurons, activation, kernel, optimizer, learning_rate, batch_size, epochs,
              layers1, layers2, normalization, dropout, dropout_rate): 
    optimizerL = ['SGD', 'Adam', 'RMSprop', 'Adadelta', 'Adagrad', 'Adamax', 'Nadam', 'Ftrl']
    #optimizerD= {'Adam':Adam(lr=learning_rate), 'SGD':SGD(lr=learning_rate),
                 #'RMSprop':RMSprop(lr=learning_rate), 'Adadelta':Adadelta(lr=learning_rate),
                 #'Adagrad':Adagrad(lr=learning_rate), 'Adamax':Adamax(lr=learning_rate),
                 #'Nadam':Nadam(lr=learning_rate), 'Ftrl':Ftrl(lr=learning_rate)}
    activationL = ['relu', 'sigmoid', 'softplus', 'softsign', 'tanh', 'selu',
                   'elu', 'exponential', LeakyReLU,'relu']
    
    neurons = round(neurons)
    kernel = round(kernel)
    activation = activationL[round(activation)]
    optimizer = optimizerL[round(optimizer)]
    batch_size = round(batch_size)
    
    epochs = round(epochs)
    layers1 = round(layers1)
    layers2 = round(layers2)
    
    def rnn_model():
        model = Sequential()
        model.add(LSTM(neurons, input_shape=(timesteps, input_dim)))
        #model.add(Conv1D(32, kernel_size=1,activation='relu', input_shape=(timesteps, input_dim)))
        
        if normalization > 0.5:
            model.add(BatchNormalization())
        for i in range(layers1):
            model.add(Dense(neurons, activation=activation)) #(neurons, activation=activation))
        if dropout > 0.5:
            model.add(Dropout(dropout_rate, seed=123))
        for i in range(layers2):
            model.add(Dense(neurons, activation=activation))
        model.add(Dropout(0.5))
        model.add(Dense(n_classes, activation='sigmoid'))
        #model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy']) #categorical_crossentropy
        model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer, metrics=['accuracy']) #categorical_crossentropy
        return model
    es = EarlyStopping(monitor='accuracy', mode='max', verbose=2, patience=20)
    nn = KerasClassifier(build_fn=rnn_model, epochs=epochs, batch_size=batch_size, verbose=2)
    kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
    score = cross_val_score(nn, X_train, y_train, scoring=score_acc, cv=kfold, fit_params={'callbacks':[es]}).mean()
    return score

In [46]:
start = time.time()
params ={
    'neurons': (10, 100),
    'kernel': (1, 3),
    'activation':(0, 9),
    'optimizer':(0,7),
    'learning_rate':(0.01, 1),
    'batch_size': (200, 1000),
    'epochs':(20, 50),
    'layers1':(1,3),
    'layers2':(1,3),
    'normalization':(0,1),
    'dropout':(0,1),
    'dropout_rate':(0,0.3)
}
# Run Bayesian Optimization
nn_opt = BayesianOptimization(bay_area, params, random_state=42)
nn_opt.maximize(init_points=15, n_iter=4)
print('Search took %s minutes' % ((time.time() - start)/60))

|   iter    |  target   |  neurons  |  kernel   | activa... | optimizer | learni... | batch_... |  epochs   |  layers1  |  layers2  | normal... |  dropout  | dropou... |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Epoch 1/22
43/43 - 6s - 150ms/step - accuracy: 0.6440 - loss: nan
Epoch 2/22
43/43 - 1s - 30ms/step - accuracy: 0.6440 - loss: nan
Epoch 3/22
43/43 - 1s - 31ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/22
43/43 - 1s - 30ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/22
43/43 - 1s - 30ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/22
43/43 - 1s - 28ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/22
43/43 - 1s - 31ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/22
43/43 - 2s - 36ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/22
43/43 - 2s - 55ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/22
43/43 - 2s - 57ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/22
43/43 - 1s - 30ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/22
43/43 - 1s - 33ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/22
43/43 - 1s - 35ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/22
43/43 - 1s - 35ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/22
43/43 - 1s - 30ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/22
43/43 - 1s - 22ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/22
43/43 - 1s - 30ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/22
43/43 - 1s - 33ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/22
43/43 - 1s - 26ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/22
43/43 - 1s - 28ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/22
43/43 - 1s - 21ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/22
43/43 - 2s - 42ms/step - accuracy: 0.6440 - loss: nan
11/11 - 2s - 164ms/step
Epoch 1/22
43/43 - 8s - 177ms/step - accuracy: 0.6438 - loss: nan
Epoch 2/22
43/43 - 1s - 29ms/step - accuracy: 0.6440 - loss: nan
Epoch 3/22
43/43 - 1s - 30ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/22
43/43 - 1s - 30ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/22
43/43 - 2s - 43ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/22
43/43 - 1s - 34ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/22
43/43 - 2s - 55ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/22
43/43 - 1s - 22ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/22
43/43 - 2s - 37ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/22
43/43 - 1s - 31ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/22
43/43 - 1s - 29ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/22
43/43 - 1s - 31ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/22
43/43 - 1s - 30ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/22
43/43 - 1s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/22
43/43 - 2s - 40ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/22
43/43 - 2s - 37ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/22
43/43 - 3s - 63ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/22
43/43 - 1s - 26ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/22
43/43 - 1s - 29ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/22
43/43 - 1s - 22ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/22
43/43 - 2s - 41ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/22
43/43 - 1s - 33ms/step - accuracy: 0.6440 - loss: nan
11/11 - 1s - 122ms/step
Epoch 1/22
43/43 - 6s - 130ms/step - accuracy: 0.6439 - loss: nan
Epoch 2/22
43/43 - 2s - 42ms/step - accuracy: 0.6439 - loss: nan
Epoch 3/22
43/43 - 1s - 31ms/step - accuracy: 0.6439 - loss: nan
Epoch 4/22
43/43 - 1s - 31ms/step - accuracy: 0.6439 - loss: nan
Epoch 5/22
43/43 - 1s - 28ms/step - accuracy: 0.6439 - loss: nan
Epoch 6/22
43/43 - 1s - 34ms/step - accuracy: 0.6439 - loss: nan
Epoch 7/22
43/43 - 1s - 26ms/step - accuracy: 0.6439 - loss: nan
Epoch 8/22
43/43 - 1s - 26ms/step - accuracy: 0.6439 - loss: nan
Epoch 9/22
43/43 - 1s - 30ms/step - accuracy: 0.6439 - loss: nan
Epoch 10/22
43/43 - 1s - 26ms/step - accuracy: 0.6439 - loss: nan
Epoch 11/22
43/43 - 1s - 31ms/step - accuracy: 0.6439 - loss: nan
Epoch 12/22
43/43 - 2s - 39ms/step - accuracy: 0.6439 - loss: nan
Epoch 13/22
43/43 - 2s - 36ms/step - accuracy: 0.6439 - loss: nan
Epoch 14/22
43/43 - 2s - 51ms/step - accuracy: 0.6439 - loss: nan
Epoch 15/22
43/43 - 2s - 36ms/step - accuracy: 0.6439 - loss: nan
Epoch 16/22
43/43 - 2s - 40ms/step - accuracy: 0.6439 - loss: nan
Epoch 17/22
43/43 - 1s - 30ms/step - accuracy: 0.6439 - loss: nan
Epoch 18/22
43/43 - 1s - 28ms/step - accuracy: 0.6439 - loss: nan
Epoch 19/22
43/43 - 1s - 28ms/step - accuracy: 0.6439 - loss: nan
Epoch 20/22
43/43 - 1s - 28ms/step - accuracy: 0.6439 - loss: nan
Epoch 21/22
43/43 - 1s - 23ms/step - accuracy: 0.6439 - loss: nan
Epoch 22/22
43/43 - 1s - 20ms/step - accuracy: 0.6439 - loss: nan
11/11 - 1s - 74ms/step
Epoch 1/22
43/43 - 6s - 146ms/step - accuracy: 0.6440 - loss: nan
Epoch 2/22
43/43 - 1s - 22ms/step - accuracy: 0.6440 - loss: nan
Epoch 3/22
43/43 - 1s - 31ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/22
43/43 - 2s - 38ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/22
43/43 - 1s - 32ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/22
43/43 - 2s - 35ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/22
43/43 - 2s - 50ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/22
43/43 - 2s - 37ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/22
43/43 - 2s - 35ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/22
43/43 - 1s - 30ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/22
43/43 - 1s - 20ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/22
43/43 - 1s - 22ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/22
43/43 - 2s - 38ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/22
43/43 - 1s - 32ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/22
43/43 - 2s - 53ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/22
43/43 - 2s - 36ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/22
43/43 - 1s - 22ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/22
43/43 - 1s - 22ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/22
43/43 - 1s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/22
43/43 - 1s - 31ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/22
43/43 - 1s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/22
43/43 - 2s - 41ms/step - accuracy: 0.6440 - loss: nan
11/11 - 1s - 108ms/step
Epoch 1/22
43/43 - 8s - 182ms/step - accuracy: 0.6439 - loss: nan
Epoch 2/22
43/43 - 1s - 31ms/step - accuracy: 0.6439 - loss: nan
Epoch 3/22
43/43 - 2s - 42ms/step - accuracy: 0.6439 - loss: nan
Epoch 4/22
43/43 - 3s - 73ms/step - accuracy: 0.6439 - loss: nan
Epoch 5/22
43/43 - 3s - 69ms/step - accuracy: 0.6439 - loss: nan
Epoch 6/22
43/43 - 3s - 69ms/step - accuracy: 0.6439 - loss: nan
Epoch 7/22
43/43 - 2s - 58ms/step - accuracy: 0.6439 - loss: nan
Epoch 8/22
43/43 - 3s - 59ms/step - accuracy: 0.6439 - loss: nan
Epoch 9/22
43/43 - 1s - 34ms/step - accuracy: 0.6439 - loss: nan
Epoch 10/22
43/43 - 2s - 36ms/step - accuracy: 0.6439 - loss: nan
Epoch 11/22
43/43 - 2s - 51ms/step - accuracy: 0.6439 - loss: nan
Epoch 12/22
43/43 - 1s - 31ms/step - accuracy: 0.6439 - loss: nan
Epoch 13/22
43/43 - 2s - 42ms/step - accuracy: 0.6439 - loss: nan
Epoch 14/22
43/43 - 1s - 31ms/step - accuracy: 0.6439 - loss: nan
Epoch 15/22
43/43 - 1s - 33ms/step - accuracy: 0.6439 - loss: nan
Epoch 16/22
43/43 - 1s - 32ms/step - accuracy: 0.6439 - loss: nan
Epoch 17/22
43/43 - 2s - 52ms/step - accuracy: 0.6439 - loss: nan
Epoch 18/22
43/43 - 1s - 23ms/step - accuracy: 0.6439 - loss: nan
Epoch 19/22
43/43 - 2s - 37ms/step - accuracy: 0.6439 - loss: nan
Epoch 20/22
43/43 - 1s - 32ms/step - accuracy: 0.6439 - loss: nan
Epoch 21/22
43/43 - 1s - 33ms/step - accuracy: 0.6439 - loss: nan
Epoch 22/22
43/43 - 1s - 30ms/step - accuracy: 0.6439 - loss: nan
11/11 - 1s - 98ms/step
| 1         | 0.6439693 | 43.708610 | 2.9014286 | 6.5879454 | 4.1906093 | 0.1644584 | 324.79561 | 21.742508 | 2.7323522 | 2.2022300 | 0.7080725 | 0.0205844 | 0.2909729 |
Epoch 1/33
23/23 - 7s - 324ms/step - accuracy: 0.4970 - loss: 1.8103
Epoch 2/33
23/23 - 3s - 125ms/step - accuracy: 0.6165 - loss: 1.2776
Epoch 3/33
23/23 - 3s - 147ms/step - accuracy: 0.6170 - loss: 1.1490
Epoch 4/33
23/23 - 2s - 93ms/step - accuracy: 0.6269 - loss: 1.0948
Epoch 5/33
23/23 - 2s - 103ms/step - accuracy: 0.6417 - loss: 1.0532
Epoch 6/33
23/23 - 3s - 138ms/step - accuracy: 0.6613 - loss: 1.0100
Epoch 7/33
23/23 - 2s - 95ms/step - accuracy: 0.6913 - loss: 0.9496
Epoch 8/33
23/23 - 2s - 75ms/step - accuracy: 0.7146 - loss: 0.8884
Epoch 9/33
23/23 - 3s - 145ms/step - accuracy: 0.7365 - loss: 0.8435
Epoch 10/33
23/23 - 3s - 110ms/step - accuracy: 0.7454 - loss: 0.8038
Epoch 11/33
23/23 - 2s - 83ms/step - accuracy: 0.7611 - loss: 0.7637
Epoch 12/33
23/23 - 2s - 71ms/step - accuracy: 0.7714 - loss: 0.7333
Epoch 13/33
23/23 - 2s - 95ms/step - accuracy: 0.7720 - loss: 0.7300
Epoch 14/33
23/23 - 2s - 106ms/step - accuracy: 0.7767 - loss: 0.7062
Epoch 15/33
23/23 - 2s - 66ms/step - accuracy: 0.7826 - loss: 0.6922
Epoch 16/33
23/23 - 2s - 87ms/step - accuracy: 0.7847 - loss: 0.6890
Epoch 17/33
23/23 - 2s - 100ms/step - accuracy: 0.7837 - loss: 0.6832
Epoch 18/33
23/23 - 2s - 100ms/step - accuracy: 0.7970 - loss: 0.6655
Epoch 19/33
23/23 - 3s - 120ms/step - accuracy: 0.7950 - loss: 0.6599
Epoch 20/33
23/23 - 2s - 90ms/step - accuracy: 0.7883 - loss: 0.6605
Epoch 21/33
23/23 - 2s - 66ms/step - accuracy: 0.7997 - loss: 0.6379
Epoch 22/33
23/23 - 2s - 72ms/step - accuracy: 0.8016 - loss: 0.6295
Epoch 23/33
23/23 - 3s - 124ms/step - accuracy: 0.8041 - loss: 0.6262
Epoch 24/33
23/23 - 3s - 136ms/step - accuracy: 0.8001 - loss: 0.6250
Epoch 25/33
23/23 - 2s - 82ms/step - accuracy: 0.8043 - loss: 0.6190
Epoch 26/33
23/23 - 2s - 86ms/step - accuracy: 0.8125 - loss: 0.6030
Epoch 27/33
23/23 - 3s - 132ms/step - accuracy: 0.8075 - loss: 0.6013
Epoch 28/33
23/23 - 3s - 109ms/step - accuracy: 0.8131 - loss: 0.5921
Epoch 29/33
23/23 - 2s - 70ms/step - accuracy: 0.8138 - loss: 0.5836
Epoch 30/33
23/23 - 4s - 154ms/step - accuracy: 0.8155 - loss: 0.5829
Epoch 31/33
23/23 - 2s - 106ms/step - accuracy: 0.8118 - loss: 0.5937
Epoch 32/33
23/23 - 2s - 94ms/step - accuracy: 0.8162 - loss: 0.5686
Epoch 33/33
23/23 - 2s - 94ms/step - accuracy: 0.8217 - loss: 0.5641
6/6 - 1s - 248ms/step
Epoch 1/33
23/23 - 8s - 341ms/step - accuracy: 0.4553 - loss: 1.9287
Epoch 2/33
23/23 - 2s - 92ms/step - accuracy: 0.5999 - loss: 1.3187
Epoch 3/33
23/23 - 2s - 98ms/step - accuracy: 0.6165 - loss: 1.1564
Epoch 4/33
23/23 - 2s - 97ms/step - accuracy: 0.6266 - loss: 1.1000
Epoch 5/33
23/23 - 2s - 108ms/step - accuracy: 0.6504 - loss: 1.0506
Epoch 6/33
23/23 - 2s - 102ms/step - accuracy: 0.6621 - loss: 1.0122
Epoch 7/33
23/23 - 4s - 165ms/step - accuracy: 0.6865 - loss: 0.9634
Epoch 8/33
23/23 - 5s - 198ms/step - accuracy: 0.7083 - loss: 0.8949
Epoch 9/33
23/23 - 2s - 92ms/step - accuracy: 0.7300 - loss: 0.8408
Epoch 10/33
23/23 - 3s - 116ms/step - accuracy: 0.7409 - loss: 0.8193
Epoch 11/33
23/23 - 2s - 67ms/step - accuracy: 0.7480 - loss: 0.7950
Epoch 12/33
23/23 - 3s - 148ms/step - accuracy: 0.7618 - loss: 0.7525
Epoch 13/33
23/23 - 3s - 120ms/step - accuracy: 0.7632 - loss: 0.7446
Epoch 14/33
23/23 - 2s - 82ms/step - accuracy: 0.7701 - loss: 0.7238
Epoch 15/33
23/23 - 2s - 69ms/step - accuracy: 0.7759 - loss: 0.7039
Epoch 16/33
23/23 - 2s - 95ms/step - accuracy: 0.7796 - loss: 0.6937
Epoch 17/33
23/23 - 3s - 116ms/step - accuracy: 0.7843 - loss: 0.6735
Epoch 18/33
23/23 - 2s - 94ms/step - accuracy: 0.7851 - loss: 0.6747
Epoch 19/33
23/23 - 2s - 91ms/step - accuracy: 0.7950 - loss: 0.6495
Epoch 20/33
23/23 - 2s - 98ms/step - accuracy: 0.7990 - loss: 0.6422
Epoch 21/33
23/23 - 3s - 124ms/step - accuracy: 0.7950 - loss: 0.6434
Epoch 22/33
23/23 - 2s - 88ms/step - accuracy: 0.7997 - loss: 0.6340
Epoch 23/33
23/23 - 3s - 124ms/step - accuracy: 0.8021 - loss: 0.6156
Epoch 24/33
23/23 - 2s - 107ms/step - accuracy: 0.8054 - loss: 0.6147
Epoch 25/33
23/23 - 2s - 69ms/step - accuracy: 0.8048 - loss: 0.6162
Epoch 26/33
23/23 - 2s - 91ms/step - accuracy: 0.8078 - loss: 0.6066
Epoch 27/33
23/23 - 2s - 106ms/step - accuracy: 0.8135 - loss: 0.5916
Epoch 28/33
23/23 - 2s - 99ms/step - accuracy: 0.8136 - loss: 0.5916
Epoch 29/33
23/23 - 3s - 121ms/step - accuracy: 0.8118 - loss: 0.5873
Epoch 30/33
23/23 - 2s - 90ms/step - accuracy: 0.8172 - loss: 0.5738
Epoch 31/33
23/23 - 3s - 121ms/step - accuracy: 0.8202 - loss: 0.5721
Epoch 32/33
23/23 - 3s - 112ms/step - accuracy: 0.8195 - loss: 0.5642
Epoch 33/33
23/23 - 4s - 164ms/step - accuracy: 0.8234 - loss: 0.5593
WARNING:tensorflow:5 out of the last 18 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000001A9A02DA700> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
6/6 - 1s - 135ms/step
Epoch 1/33
23/23 - 9s - 372ms/step - accuracy: 0.4529 - loss: 1.9428
Epoch 2/33
23/23 - 2s - 68ms/step - accuracy: 0.6092 - loss: 1.2768
Epoch 3/33
23/23 - 2s - 102ms/step - accuracy: 0.6181 - loss: 1.1513
Epoch 4/33
23/23 - 3s - 118ms/step - accuracy: 0.6359 - loss: 1.0920
Epoch 5/33
23/23 - 3s - 123ms/step - accuracy: 0.6551 - loss: 1.0426
Epoch 6/33
23/23 - 2s - 93ms/step - accuracy: 0.6691 - loss: 0.9966
Epoch 7/33
23/23 - 2s - 91ms/step - accuracy: 0.6869 - loss: 0.9362
Epoch 8/33
23/23 - 2s - 86ms/step - accuracy: 0.7048 - loss: 0.8935
Epoch 9/33
23/23 - 2s - 96ms/step - accuracy: 0.7232 - loss: 0.8529
Epoch 10/33
23/23 - 3s - 152ms/step - accuracy: 0.7386 - loss: 0.8135
Epoch 11/33
23/23 - 2s - 101ms/step - accuracy: 0.7481 - loss: 0.7874
Epoch 12/33
23/23 - 2s - 76ms/step - accuracy: 0.7516 - loss: 0.8019
Epoch 13/33
23/23 - 2s - 89ms/step - accuracy: 0.7593 - loss: 0.7741
Epoch 14/33
23/23 - 3s - 135ms/step - accuracy: 0.7680 - loss: 0.7462
Epoch 15/33
23/23 - 2s - 99ms/step - accuracy: 0.7713 - loss: 0.7216
Epoch 16/33
23/23 - 3s - 112ms/step - accuracy: 0.7826 - loss: 0.6988
Epoch 17/33
23/23 - 5s - 227ms/step - accuracy: 0.7871 - loss: 0.6792
Epoch 18/33
23/23 - 2s - 90ms/step - accuracy: 0.7871 - loss: 0.6704
Epoch 19/33
23/23 - 3s - 147ms/step - accuracy: 0.7943 - loss: 0.6633
Epoch 20/33
23/23 - 2s - 96ms/step - accuracy: 0.7962 - loss: 0.6467
Epoch 21/33
23/23 - 3s - 129ms/step - accuracy: 0.7955 - loss: 0.6518
Epoch 22/33
23/23 - 3s - 129ms/step - accuracy: 0.7956 - loss: 0.6525
Epoch 23/33
23/23 - 2s - 87ms/step - accuracy: 0.8050 - loss: 0.6241
Epoch 24/33
23/23 - 3s - 139ms/step - accuracy: 0.8065 - loss: 0.6102
Epoch 25/33
23/23 - 3s - 115ms/step - accuracy: 0.8107 - loss: 0.6058
Epoch 26/33
23/23 - 2s - 96ms/step - accuracy: 0.8127 - loss: 0.6015
Epoch 27/33
23/23 - 2s - 74ms/step - accuracy: 0.8176 - loss: 0.5887
Epoch 28/33
23/23 - 2s - 93ms/step - accuracy: 0.8145 - loss: 0.5941
Epoch 29/33
23/23 - 3s - 122ms/step - accuracy: 0.8226 - loss: 0.5778
Epoch 30/33
23/23 - 2s - 100ms/step - accuracy: 0.8252 - loss: 0.5713
Epoch 31/33
23/23 - 2s - 66ms/step - accuracy: 0.8177 - loss: 0.5884
Epoch 32/33
23/23 - 3s - 137ms/step - accuracy: 0.8208 - loss: 0.5772
Epoch 33/33
23/23 - 2s - 78ms/step - accuracy: 0.8237 - loss: 0.5569
WARNING:tensorflow:5 out of the last 13 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000001A995618720> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
6/6 - 1s - 177ms/step
Epoch 1/33
23/23 - 10s - 447ms/step - accuracy: 0.4683 - loss: 2.0575
Epoch 2/33
23/23 - 2s - 97ms/step - accuracy: 0.6102 - loss: 1.2782
Epoch 3/33
23/23 - 2s - 88ms/step - accuracy: 0.6179 - loss: 1.1443
Epoch 4/33
23/23 - 3s - 120ms/step - accuracy: 0.6314 - loss: 1.0860
Epoch 5/33
23/23 - 3s - 129ms/step - accuracy: 0.6368 - loss: 1.0497
Epoch 6/33
23/23 - 3s - 112ms/step - accuracy: 0.6530 - loss: 1.0097
Epoch 7/33
23/23 - 2s - 92ms/step - accuracy: 0.6656 - loss: 0.9708
Epoch 8/33
23/23 - 2s - 98ms/step - accuracy: 0.6903 - loss: 0.9034
Epoch 9/33
23/23 - 2s - 97ms/step - accuracy: 0.7035 - loss: 0.8690
Epoch 10/33
23/23 - 2s - 77ms/step - accuracy: 0.7293 - loss: 0.8206
Epoch 11/33
23/23 - 3s - 130ms/step - accuracy: 0.7458 - loss: 0.7859
Epoch 12/33
23/23 - 2s - 92ms/step - accuracy: 0.7533 - loss: 0.7534
Epoch 13/33
23/23 - 2s - 95ms/step - accuracy: 0.7617 - loss: 0.7404
Epoch 14/33
23/23 - 2s - 74ms/step - accuracy: 0.7699 - loss: 0.7271
Epoch 15/33
23/23 - 1s - 61ms/step - accuracy: 0.7712 - loss: 0.7180
Epoch 16/33
23/23 - 3s - 146ms/step - accuracy: 0.7805 - loss: 0.6904
Epoch 17/33
23/23 - 2s - 89ms/step - accuracy: 0.7863 - loss: 0.6745
Epoch 18/33
23/23 - 2s - 82ms/step - accuracy: 0.7903 - loss: 0.6666
Epoch 19/33
23/23 - 3s - 130ms/step - accuracy: 0.7923 - loss: 0.6518
Epoch 20/33
23/23 - 2s - 102ms/step - accuracy: 0.7939 - loss: 0.6454
Epoch 21/33
23/23 - 2s - 90ms/step - accuracy: 0.7951 - loss: 0.6462
Epoch 22/33
23/23 - 3s - 114ms/step - accuracy: 0.8003 - loss: 0.6231
Epoch 23/33
23/23 - 3s - 116ms/step - accuracy: 0.7985 - loss: 0.6332
Epoch 24/33
23/23 - 3s - 146ms/step - accuracy: 0.8017 - loss: 0.6254
Epoch 25/33
23/23 - 2s - 74ms/step - accuracy: 0.8102 - loss: 0.6033
Epoch 26/33
23/23 - 3s - 124ms/step - accuracy: 0.8076 - loss: 0.6031
Epoch 27/33
23/23 - 3s - 113ms/step - accuracy: 0.8117 - loss: 0.5939
Epoch 28/33
23/23 - 2s - 91ms/step - accuracy: 0.8142 - loss: 0.5856
Epoch 29/33
23/23 - 2s - 90ms/step - accuracy: 0.8102 - loss: 0.6041
Epoch 30/33
23/23 - 2s - 89ms/step - accuracy: 0.8174 - loss: 0.5762
Epoch 31/33
23/23 - 3s - 152ms/step - accuracy: 0.8171 - loss: 0.5807
Epoch 32/33
23/23 - 2s - 106ms/step - accuracy: 0.8165 - loss: 0.5760
Epoch 33/33
23/23 - 2s - 95ms/step - accuracy: 0.8240 - loss: 0.5629
6/6 - 1s - 235ms/step
Epoch 1/33
23/23 - 9s - 396ms/step - accuracy: 0.4526 - loss: 1.9342
Epoch 2/33
23/23 - 2s - 85ms/step - accuracy: 0.6007 - loss: 1.2933
Epoch 3/33
23/23 - 3s - 132ms/step - accuracy: 0.6138 - loss: 1.1302
Epoch 4/33
23/23 - 3s - 119ms/step - accuracy: 0.6403 - loss: 1.0684
Epoch 5/33
23/23 - 2s - 107ms/step - accuracy: 0.6593 - loss: 1.0071
Epoch 6/33
23/23 - 3s - 111ms/step - accuracy: 0.6812 - loss: 0.9407
Epoch 7/33
23/23 - 3s - 125ms/step - accuracy: 0.7006 - loss: 0.8895
Epoch 8/33
23/23 - 2s - 104ms/step - accuracy: 0.7231 - loss: 0.8479
Epoch 9/33
23/23 - 3s - 117ms/step - accuracy: 0.7327 - loss: 0.8162
Epoch 10/33
23/23 - 2s - 76ms/step - accuracy: 0.7423 - loss: 0.7954
Epoch 11/33
23/23 - 3s - 120ms/step - accuracy: 0.7515 - loss: 0.7672
Epoch 12/33
23/23 - 2s - 105ms/step - accuracy: 0.7583 - loss: 0.7499
Epoch 13/33
23/23 - 2s - 74ms/step - accuracy: 0.7670 - loss: 0.7313
Epoch 14/33
23/23 - 3s - 140ms/step - accuracy: 0.7747 - loss: 0.7034
Epoch 15/33
23/23 - 3s - 130ms/step - accuracy: 0.7808 - loss: 0.6867
Epoch 16/33
23/23 - 2s - 95ms/step - accuracy: 0.7844 - loss: 0.6721
Epoch 17/33
23/23 - 3s - 136ms/step - accuracy: 0.7921 - loss: 0.6590
Epoch 18/33
23/23 - 2s - 76ms/step - accuracy: 0.7938 - loss: 0.6506
Epoch 19/33
23/23 - 3s - 134ms/step - accuracy: 0.7958 - loss: 0.6404
Epoch 20/33
23/23 - 3s - 117ms/step - accuracy: 0.8027 - loss: 0.6274
Epoch 21/33
23/23 - 2s - 106ms/step - accuracy: 0.7963 - loss: 0.6347
Epoch 22/33

ValueError: Input y contains NaN.

In [48]:
optimum = nn_opt.max['params']
learning_rate = optimum['learning_rate']
activationL = ['relu', 'sigmoid', 'softplus', 'softsign', 'tanh', 'selu',
               'elu', 'exponential', LeakyReLU,'relu']
optimum['activation'] = activationL[round(optimum['activation'])]
optimum['batch_size'] = round(optimum['batch_size'])
optimum['epochs'] = round(optimum['epochs'])
optimum['layers1'] = round(optimum['layers1'])
optimum['layers2'] = round(optimum['layers2'])
optimum['neurons'] = round(optimum['neurons'])
optimizerL = ['Adam', 'SGD', 'RMSprop', 'Adadelta', 'Adagrad', 'Adamax', 'Nadam', 'Ftrl','Adam']
optimizerD= {'Adam':Adam(learning_rate=learning_rate), 'SGD':SGD(learning_rate=learning_rate),
             'RMSprop':RMSprop(learning_rate=learning_rate), 'Adadelta':Adadelta(learning_rate=learning_rate),
             'Adagrad':Adagrad(learning_rate=learning_rate), 'Adamax':Adamax(learning_rate=learning_rate),
             'Nadam':Nadam(learning_rate=learning_rate), 'Ftrl':Ftrl(learning_rate=learning_rate)}
optimum['optimizer'] = optimizerD[optimizerL[round(optimum['optimizer'])]]
optimum

{'neurons': 37,
 'kernel': 1.1953442280127677,
 'activation': 'elu',
 'optimizer': <keras.src.optimizers.adadelta.Adadelta at 0x1aa0d6aa750>,
 'learning_rate': 0.13081785249633104,
 'batch_size': 596,
 'epochs': 21,
 'layers1': 3,
 'layers2': 2,
 'normalization': 0.662522284353982,
 'dropout': 0.31171107608941095,
 'dropout_rate': 0.15602040635334324}

#### 7. Running RNN with optimized hyperparameters

In [50]:
# Creating the model with optimized hyperparameters and compiling the model
epochs = 21
batch_size = 596

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = 15
layers1 = 3
layers2 = 2
activation = 'elu'
kernel = 1.1953442280127677
neurons = 37
normalization = 0.662522284353982
dropout = 0.31171107608941095
dropout_rate = 0.15602040635334324
optimizer = 'Adadelta'

model = Sequential()
model.add(LSTM(neurons, input_shape=(timesteps, input_dim)))
if normalization > 0.5:
    model.add(BatchNormalization())
for i in range(layers1):
    model.add(Dense(neurons, activation=activation))
if dropout > 0.5:
    model.add(Dropout(dropout_rate, seed=123))
for i in range(layers2):
    model.add(Dense(neurons, activation=activation))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='sigmoid'))
model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])

In [52]:
# Viewing the model summary
model.summary()

Model: "sequential_75"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_75 (LSTM)                  │ (None, 37)             │         6,956 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_40          │ (None, 37)             │           148 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_385 (Dense)               │ (None, 37)             │         1,406 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_386 (Dense)               │ (None, 37)             │         1,406 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_387 (Dense)               │ (None, 37)             │         1,406 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_388 (Dense)               │ (None, 37)             │         1,406 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_389 (Dense)               │ (None, 37)             │         1,406 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_105 (Dropout)           │ (None, 37)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_390 (Dense)               │ (None, 15)             │           570 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 14,704 (57.44 KB)

 Trainable params: 14,630 (57.15 KB)

 Non-trainable params: 74 (296.00 B)

In [54]:
# Turning y_test into one-hot format
ty = to_categorical(y_test)
print(ty)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]

In [56]:
# Fitting the model
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/21
29/29 - 6s - 222ms/step - accuracy: 0.0568 - loss: 2.8644
Epoch 2/21
29/29 - 2s - 56ms/step - accuracy: 0.0602 - loss: 2.8558
Epoch 3/21
29/29 - 1s - 35ms/step - accuracy: 0.0583 - loss: 2.8533
Epoch 4/21
29/29 - 1s - 32ms/step - accuracy: 0.0575 - loss: 2.8486
Epoch 5/21
29/29 - 1s - 46ms/step - accuracy: 0.0594 - loss: 2.8427
Epoch 6/21
29/29 - 2s - 85ms/step - accuracy: 0.0571 - loss: 2.8385
Epoch 7/21
29/29 - 1s - 41ms/step - accuracy: 0.0623 - loss: 2.8327
Epoch 8/21
29/29 - 2s - 52ms/step - accuracy: 0.0650 - loss: 2.8265
Epoch 9/21
29/29 - 1s - 46ms/step - accuracy: 0.0643 - loss: 2.8217
Epoch 10/21
29/29 - 1s - 44ms/step - accuracy: 0.0637 - loss: 2.8140
Epoch 11/21
29/29 - 1s - 45ms/step - accuracy: 0.0640 - loss: 2.8130
Epoch 12/21
29/29 - 1s - 45ms/step - accuracy: 0.0679 - loss: 2.8005
Epoch 13/21
29/29 - 1s - 33ms/step - accuracy: 0.0689 - loss: 2.8024
Epoch 14/21
29/29 - 1s - 32ms/step - accuracy: 0.0690 - loss: 2.7870
Epoch 15/21
29/29 - 1s - 43ms/step - accuracy: 0.0747 - loss: 2.7827
Epoch 16/21
29/29 - 1s - 46ms/step - accuracy: 0.0698 - loss: 2.7804
Epoch 17/21
29/29 - 1s - 49ms/step - accuracy: 0.0759 - loss: 2.7708
Epoch 18/21
29/29 - 1s - 51ms/step - accuracy: 0.0738 - loss: 2.7681
Epoch 19/21
29/29 - 1s - 47ms/step - accuracy: 0.0756 - loss: 2.7588
Epoch 20/21
29/29 - 1s - 39ms/step - accuracy: 0.0770 - loss: 2.7594
Epoch 21/21
29/29 - 2s - 54ms/step - accuracy: 0.0828 - loss: 2.7506

#### 8. Confusion matrix

In [58]:
# Defining a list of stations names
stations = {0: 'BASEL', 1: 'BELGRADE', 2: 'BUDAPEST', 3: 'DEBILT', 4: 'DUSSELDORF', 5: 'HEATHROW', 6: 'KASSEL', 7: 'LJUBLJANA', 8: 'MAASTRICHT',
9: 'MADRID', 10: 'MUNCHENB', 11: 'OSLO', 12: 'SONNBLICK', 13: 'STOCKHOLM', 14: 'VALENTIA'}

In [60]:
# Creating a confusion matrix by checking if y_true and y_pred are one-hot encoded
def confusion_matrix(y_true, y_pred, stations):
    if y_true.ndim == 1:
        y_true_labels = y_true
    else:
        y_true_labels = np.argmax(y_true, axis=1)
    
    if y_pred.ndim == 1:
        y_pred_labels = y_pred
    else:
        y_pred_labels = np.argmax(y_pred, axis=1)
        
    y_true_series = pd.Series([stations[y] for y in y_true_labels])
    y_pred_series = pd.Series([stations[y] for y in y_pred_labels])
    
    return pd.crosstab(y_true_series, y_pred_series, rownames=['True'], colnames=['Pred'])

In [62]:
# Printing the confusion matrix
print(confusion_matrix(ty, model.predict(X_test), stations))

180/180 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step
Pred        BASEL  BELGRADE  BUDAPEST  DEBILT  DUSSELDORF  HEATHROW  KASSEL  \
True
BASEL         346       218      1007     170          16       255     266
BELGRADE        7        78       626       4           4         2      86
BUDAPEST        1        23        90       0           0         0      17
DEBILT          0        11        33       0           0         0       2
DUSSELDORF      0         2        16       0           0         0       0
HEATHROW        0        17        24       1           1         2       6
KASSEL          1         0         6       0           0         0       2
LJUBLJANA       0         7        30       0           0         1       4
MAASTRICHT      0         0         7       0           0         0       0
MADRID          5        17       159       0           4        40      28
MUNCHENB        1         1         5       0           0         0       0
OSLO            0         1         1       0           0         0       3
STOCKHOLM       0         0         0       0           0         0       1
VALENTIA        0         0         0       0           0         0       0

Pred        LJUBLJANA  MAASTRICHT  MADRID  OSLO  SONNBLICK  STOCKHOLM  \
True
BASEL              73         334     102   139        252        341
BELGRADE           12          10      44    41        140         28
BUDAPEST            3           3      15    22         28          9
DEBILT              6           0       4    11         13          2
DUSSELDORF          0           1       1     4          2          3
HEATHROW            1           2       5     6          8          5
KASSEL              0           0       0     0          2          0
LJUBLJANA           0           6       0     6          7          0
MAASTRICHT          0           0       0     1          0          0
MADRID              8          53      25    37         40         31
MUNCHENB            0           0       0     0          1          0
OSLO                0           0       0     0          0          0
STOCKHOLM           0           0       1     1          1          0
VALENTIA            0           0       1     0          0          0

Pred        VALENTIA
True
BASEL            163
BELGRADE          10
BUDAPEST           3
DEBILT             0
DUSSELDORF         0
HEATHROW           4
KASSEL             0
LJUBLJANA          0
MAASTRICHT         1
MADRID            11
MUNCHENB           0
OSLO               0
STOCKHOLM          0
VALENTIA           0